import type { Metadata } from 'next'
import { FridgeProvider } from '@/components/config/context'
import './globals.css'
import NavBar from "@/components/navbar";
import { PythonRuntimeProvider } from '@/lib/pythonrt';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PythonRuntimeProvider>
          <FridgeProvider>
              <NavBar />
              {children}
          </FridgeProvider>
        </PythonRuntimeProvider>
      </body>
    </html>
  )
}
