name: Docker Image Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:

  build-generic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build the Docker image
        run: |
          docker build . \
            --tag cryowala:latest

  build-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build the Docker image
        run: |
          docker build . \
            --build-arg BASE_PATH="/Cryowala" \
            --tag cryowala:latest
