name: Github Pages Deployment

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build the Docker image
        run: |
          docker build . \
            --build-arg BASE_PATH="/Cryowala" \
            --tag cryowala:latest
      - name: Extract the Static Files from the Image
        run: |
          docker run --rm \
            -v $(pwd)/static:/opt/mount \
             cryowala:latest \
             cp -r /usr/share/nginx/html/. /opt/mount
      - name: Upload the Static Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: static
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
